# 1. Veritaban? Ba?lant? ve Kal?c?l?k Ayarlar?
# Veriler art?k RAM'de de?il, proje klasöründeki 'diyet_db' dosyas?nda saklanacak.
spring.datasource.url=jdbc:h2:file:./diyet_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Hibernate Ayar? (Kritik Nokta)
# 'create-drop' yerine 'update' kullan?yoruz ki eski veriler silinmesin.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. H2 Console (Veritaban?n? taray?c?dan izlemek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

